In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib

plt.style.use("fivethirtyeight")

In [2]:
class Perceptron():
    def __init__(self, eta: float=None, epochs: int=None):
        self.weight = np.random.randn(3) * (1e-4)
        self.eta = eta # Learning rate
        self.epochs = epochs # iteration
        
    def fit(self, x, y):
        self.x = x
        self.y = y
        
        x_with_bais = np.c_[self.x, -np.ones((len(self.x), 1))]
        print(f"x with bias: \n{x_with_bais}")


In [3]:
obj = Perceptron(eta = 0.01, epochs= 10)

In [4]:
obj.eta

0.01

In [5]:
obj.epochs

10

In [6]:
obj.weight

array([-3.82848614e-05,  1.42218815e-05,  1.25477847e-04])

In [7]:
-np.ones((4, 1))

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [8]:
x = -np.ones((4, 2))
x

array([[-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.]])

In [9]:
y = -np.ones((4, 1))
y

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [10]:
obj.fit(x,y)

x with bias: 
[[-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]]
