In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib

plt.style.use("fivethirtyeight")

In [2]:
class Perceptron():
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * (1e-4)
        self.eta = eta # Learning rate
        self.epochs = epochs # iteration
        
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
    
    def activation_function(self, z):
        return np.where(z > 0, 1, 0)
    
    def fit(self, x, y):
        self.x = x
        self.y = y
        
        x_with_bais = np.c_[self.x, -np.ones((len(self.x), 1))]
        print(f"x with bias: \n{x_with_bais}")
        
        for epoch in range(self.epochs):
            print('--'*20)
            print(f"for  epoch >> {epoch + 1}")
            print("--"*20)
            
            z = self._z_outcome(x_with_bais, self.weights)
            y_hat = self.activation_function(z)
            print(f"Predicted value after forward pass: \n{y_hat}")
                  
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            
            self.weights = self.weights + self.eta * np.dot(x_with_bais.T, self.error)
            print(f"Updated weights after epoch: {epoch + 1}/{self.epochs}: \n{self.weights}")
            print(f"##"*20)
            
    def predict(self, x):
        x_with_bais = np.c_[x, -np.ones((len(x), 1))]
        z = self._z_outcome(x_with_bais, self.weights)
        return self.activation_function(z)


In [3]:
OR = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,1,1,1]
}

df_OR = pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [4]:
def prepare_data(df, target_col = "y"):
    x = df.drop(target_col, axis=1)
    y = df[target_col]
    
    return x, y

In [5]:
x,y = prepare_data(df_OR)

ETA = 0.1
EPOCHS = 10

model_or = Perceptron(eta=ETA, epochs=EPOCHS)

model_or.fit(x, y)

x with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
----------------------------------------
for  epoch >> 1
----------------------------------------
Predicted value after forward pass: 
[1 0 0 0]
error: 
0   -1
1    1
2    1
3    1
Name: y, dtype: int64
Updated weights after epoch: 1/10: 
[ 0.19993014  0.19993066 -0.20001279]
########################################
----------------------------------------
for  epoch >> 2
----------------------------------------
Predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights after epoch: 2/10: 
[ 0.19993014  0.19993066 -0.10001279]
########################################
----------------------------------------
for  epoch >> 3
----------------------------------------
Predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights after epoch: 3/10: 
[ 1.99930140e-01  1.99930659e-01 -1.27927293e-05]


In [6]:
model_or.predict(x=[[1,0]])

array([1])